/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips/index'
import { Route as CaptainIndexRouteImport } from './routes/captain/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TripsBookingIdRouteImport } from './routes/trips/$bookingId'
import { Route as ListingsIdRouteImport } from './routes/listings/$id'
import { Route as ConversationIdRouteImport } from './routes/conversation/$id'
import { Route as CaptainOnboardingRouteImport } from './routes/captain/onboarding'
import { Route as CaptainBookingsRouteImport } from './routes/captain/bookings'
import { Route as BookingListingIdRouteImport } from './routes/booking/$listingId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminListingsRouteImport } from './routes/admin/listings'
import { Route as AdminConversationsRouteImport } from './routes/admin/conversations'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminBoatsRouteImport } from './routes/admin/boats'
import { Route as CaptainListingsIndexRouteImport } from './routes/captain/listings/index'
import { Route as CaptainBoatsIndexRouteImport } from './routes/captain/boats/index'
import { Route as CaptainListingsNewRouteImport } from './routes/captain/listings/new'
import { Route as CaptainListingsListingIdRouteImport } from './routes/captain/listings/$listingId'
import { Route as CaptainBoatsNewRouteImport } from './routes/captain/boats/new'
import { Route as CaptainBoatsBoatIdRouteImport } from './routes/captain/boats/$boatId'
import { Route as BookingConfirmationBookingIdRouteImport } from './routes/booking/confirmation/$bookingId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainIndexRoute = CaptainIndexRouteImport.update({
  id: '/captain/',
  path: '/captain/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TripsBookingIdRoute = TripsBookingIdRouteImport.update({
  id: '/trips/$bookingId',
  path: '/trips/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationIdRoute = ConversationIdRouteImport.update({
  id: '/conversation/$id',
  path: '/conversation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainOnboardingRoute = CaptainOnboardingRouteImport.update({
  id: '/captain/onboarding',
  path: '/captain/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainBookingsRoute = CaptainBookingsRouteImport.update({
  id: '/captain/bookings',
  path: '/captain/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingListingIdRoute = BookingListingIdRouteImport.update({
  id: '/booking/$listingId',
  path: '/booking/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBoatsRoute = AdminBoatsRouteImport.update({
  id: '/boats',
  path: '/boats',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CaptainListingsIndexRoute = CaptainListingsIndexRouteImport.update({
  id: '/captain/listings/',
  path: '/captain/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainBoatsIndexRoute = CaptainBoatsIndexRouteImport.update({
  id: '/captain/boats/',
  path: '/captain/boats/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainListingsNewRoute = CaptainListingsNewRouteImport.update({
  id: '/captain/listings/new',
  path: '/captain/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainListingsListingIdRoute =
  CaptainListingsListingIdRouteImport.update({
    id: '/captain/listings/$listingId',
    path: '/captain/listings/$listingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaptainBoatsNewRoute = CaptainBoatsNewRouteImport.update({
  id: '/captain/boats/new',
  path: '/captain/boats/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainBoatsBoatIdRoute = CaptainBoatsBoatIdRouteImport.update({
  id: '/captain/boats/$boatId',
  path: '/captain/boats/$boatId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationBookingIdRoute =
  BookingConfirmationBookingIdRouteImport.update({
    id: '/booking/confirmation/$bookingId',
    path: '/booking/confirmation/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/boats': typeof AdminBoatsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$listingId': typeof BookingListingIdRoute
  '/captain/bookings': typeof CaptainBookingsRoute
  '/captain/onboarding': typeof CaptainOnboardingRoute
  '/conversation/$id': typeof ConversationIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/trips/$bookingId': typeof TripsBookingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/captain/': typeof CaptainIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/booking/confirmation/$bookingId': typeof BookingConfirmationBookingIdRoute
  '/captain/boats/$boatId': typeof CaptainBoatsBoatIdRoute
  '/captain/boats/new': typeof CaptainBoatsNewRoute
  '/captain/listings/$listingId': typeof CaptainListingsListingIdRoute
  '/captain/listings/new': typeof CaptainListingsNewRoute
  '/captain/boats/': typeof CaptainBoatsIndexRoute
  '/captain/listings/': typeof CaptainListingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/boats': typeof AdminBoatsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$listingId': typeof BookingListingIdRoute
  '/captain/bookings': typeof CaptainBookingsRoute
  '/captain/onboarding': typeof CaptainOnboardingRoute
  '/conversation/$id': typeof ConversationIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/trips/$bookingId': typeof TripsBookingIdRoute
  '/admin': typeof AdminIndexRoute
  '/captain': typeof CaptainIndexRoute
  '/trips': typeof TripsIndexRoute
  '/booking/confirmation/$bookingId': typeof BookingConfirmationBookingIdRoute
  '/captain/boats/$boatId': typeof CaptainBoatsBoatIdRoute
  '/captain/boats/new': typeof CaptainBoatsNewRoute
  '/captain/listings/$listingId': typeof CaptainListingsListingIdRoute
  '/captain/listings/new': typeof CaptainListingsNewRoute
  '/captain/boats': typeof CaptainBoatsIndexRoute
  '/captain/listings': typeof CaptainListingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/boats': typeof AdminBoatsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$listingId': typeof BookingListingIdRoute
  '/captain/bookings': typeof CaptainBookingsRoute
  '/captain/onboarding': typeof CaptainOnboardingRoute
  '/conversation/$id': typeof ConversationIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/trips/$bookingId': typeof TripsBookingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/captain/': typeof CaptainIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/booking/confirmation/$bookingId': typeof BookingConfirmationBookingIdRoute
  '/captain/boats/$boatId': typeof CaptainBoatsBoatIdRoute
  '/captain/boats/new': typeof CaptainBoatsNewRoute
  '/captain/listings/$listingId': typeof CaptainListingsListingIdRoute
  '/captain/listings/new': typeof CaptainListingsNewRoute
  '/captain/boats/': typeof CaptainBoatsIndexRoute
  '/captain/listings/': typeof CaptainListingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/help'
    | '/inbox'
    | '/profile'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/admin/boats'
    | '/admin/bookings'
    | '/admin/conversations'
    | '/admin/listings'
    | '/admin/reviews'
    | '/admin/users'
    | '/booking/$listingId'
    | '/captain/bookings'
    | '/captain/onboarding'
    | '/conversation/$id'
    | '/listings/$id'
    | '/trips/$bookingId'
    | '/admin/'
    | '/captain/'
    | '/trips/'
    | '/booking/confirmation/$bookingId'
    | '/captain/boats/$boatId'
    | '/captain/boats/new'
    | '/captain/listings/$listingId'
    | '/captain/listings/new'
    | '/captain/boats/'
    | '/captain/listings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/inbox'
    | '/profile'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/admin/boats'
    | '/admin/bookings'
    | '/admin/conversations'
    | '/admin/listings'
    | '/admin/reviews'
    | '/admin/users'
    | '/booking/$listingId'
    | '/captain/bookings'
    | '/captain/onboarding'
    | '/conversation/$id'
    | '/listings/$id'
    | '/trips/$bookingId'
    | '/admin'
    | '/captain'
    | '/trips'
    | '/booking/confirmation/$bookingId'
    | '/captain/boats/$boatId'
    | '/captain/boats/new'
    | '/captain/listings/$listingId'
    | '/captain/listings/new'
    | '/captain/boats'
    | '/captain/listings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/help'
    | '/inbox'
    | '/profile'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/admin/boats'
    | '/admin/bookings'
    | '/admin/conversations'
    | '/admin/listings'
    | '/admin/reviews'
    | '/admin/users'
    | '/booking/$listingId'
    | '/captain/bookings'
    | '/captain/onboarding'
    | '/conversation/$id'
    | '/listings/$id'
    | '/trips/$bookingId'
    | '/admin/'
    | '/captain/'
    | '/trips/'
    | '/booking/confirmation/$bookingId'
    | '/captain/boats/$boatId'
    | '/captain/boats/new'
    | '/captain/listings/$listingId'
    | '/captain/listings/new'
    | '/captain/boats/'
    | '/captain/listings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  HelpRoute: typeof HelpRoute
  InboxRoute: typeof InboxRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  BookingListingIdRoute: typeof BookingListingIdRoute
  CaptainBookingsRoute: typeof CaptainBookingsRoute
  CaptainOnboardingRoute: typeof CaptainOnboardingRoute
  ConversationIdRoute: typeof ConversationIdRoute
  ListingsIdRoute: typeof ListingsIdRoute
  TripsBookingIdRoute: typeof TripsBookingIdRoute
  CaptainIndexRoute: typeof CaptainIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
  BookingConfirmationBookingIdRoute: typeof BookingConfirmationBookingIdRoute
  CaptainBoatsBoatIdRoute: typeof CaptainBoatsBoatIdRoute
  CaptainBoatsNewRoute: typeof CaptainBoatsNewRoute
  CaptainListingsListingIdRoute: typeof CaptainListingsListingIdRoute
  CaptainListingsNewRoute: typeof CaptainListingsNewRoute
  CaptainBoatsIndexRoute: typeof CaptainBoatsIndexRoute
  CaptainListingsIndexRoute: typeof CaptainListingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/': {
      id: '/captain/'
      path: '/captain'
      fullPath: '/captain/'
      preLoaderRoute: typeof CaptainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/trips/$bookingId': {
      id: '/trips/$bookingId'
      path: '/trips/$bookingId'
      fullPath: '/trips/$bookingId'
      preLoaderRoute: typeof TripsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/$id': {
      id: '/conversation/$id'
      path: '/conversation/$id'
      fullPath: '/conversation/$id'
      preLoaderRoute: typeof ConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/onboarding': {
      id: '/captain/onboarding'
      path: '/captain/onboarding'
      fullPath: '/captain/onboarding'
      preLoaderRoute: typeof CaptainOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/bookings': {
      id: '/captain/bookings'
      path: '/captain/bookings'
      fullPath: '/captain/bookings'
      preLoaderRoute: typeof CaptainBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$listingId': {
      id: '/booking/$listingId'
      path: '/booking/$listingId'
      fullPath: '/booking/$listingId'
      preLoaderRoute: typeof BookingListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/conversations': {
      id: '/admin/conversations'
      path: '/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AdminConversationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/boats': {
      id: '/admin/boats'
      path: '/boats'
      fullPath: '/admin/boats'
      preLoaderRoute: typeof AdminBoatsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/captain/listings/': {
      id: '/captain/listings/'
      path: '/captain/listings'
      fullPath: '/captain/listings/'
      preLoaderRoute: typeof CaptainListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/boats/': {
      id: '/captain/boats/'
      path: '/captain/boats'
      fullPath: '/captain/boats/'
      preLoaderRoute: typeof CaptainBoatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/listings/new': {
      id: '/captain/listings/new'
      path: '/captain/listings/new'
      fullPath: '/captain/listings/new'
      preLoaderRoute: typeof CaptainListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/listings/$listingId': {
      id: '/captain/listings/$listingId'
      path: '/captain/listings/$listingId'
      fullPath: '/captain/listings/$listingId'
      preLoaderRoute: typeof CaptainListingsListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/boats/new': {
      id: '/captain/boats/new'
      path: '/captain/boats/new'
      fullPath: '/captain/boats/new'
      preLoaderRoute: typeof CaptainBoatsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/boats/$boatId': {
      id: '/captain/boats/$boatId'
      path: '/captain/boats/$boatId'
      fullPath: '/captain/boats/$boatId'
      preLoaderRoute: typeof CaptainBoatsBoatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirmation/$bookingId': {
      id: '/booking/confirmation/$bookingId'
      path: '/booking/confirmation/$bookingId'
      fullPath: '/booking/confirmation/$bookingId'
      preLoaderRoute: typeof BookingConfirmationBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBoatsRoute: typeof AdminBoatsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminConversationsRoute: typeof AdminConversationsRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBoatsRoute: AdminBoatsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminConversationsRoute: AdminConversationsRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  HelpRoute: HelpRoute,
  InboxRoute: InboxRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  BookingListingIdRoute: BookingListingIdRoute,
  CaptainBookingsRoute: CaptainBookingsRoute,
  CaptainOnboardingRoute: CaptainOnboardingRoute,
  ConversationIdRoute: ConversationIdRoute,
  ListingsIdRoute: ListingsIdRoute,
  TripsBookingIdRoute: TripsBookingIdRoute,
  CaptainIndexRoute: CaptainIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
  BookingConfirmationBookingIdRoute: BookingConfirmationBookingIdRoute,
  CaptainBoatsBoatIdRoute: CaptainBoatsBoatIdRoute,
  CaptainBoatsNewRoute: CaptainBoatsNewRoute,
  CaptainListingsListingIdRoute: CaptainListingsListingIdRoute,
  CaptainListingsNewRoute: CaptainListingsNewRoute,
  CaptainBoatsIndexRoute: CaptainBoatsIndexRoute,
  CaptainListingsIndexRoute: CaptainListingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
