/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaptainIndexRouteImport } from './routes/captain/index'
import { Route as ListingsIdRouteImport } from './routes/listings/$id'
import { Route as ConversationIdRouteImport } from './routes/conversation/$id'
import { Route as CaptainOnboardingRouteImport } from './routes/captain/onboarding'
import { Route as CaptainBookingsRouteImport } from './routes/captain/bookings'
import { Route as BookingListingIdRouteImport } from './routes/booking/$listingId'
import { Route as CaptainListingsIndexRouteImport } from './routes/captain/listings/index'
import { Route as CaptainBoatsIndexRouteImport } from './routes/captain/boats/index'
import { Route as CaptainListingsNewRouteImport } from './routes/captain/listings/new'
import { Route as CaptainListingsListingIdRouteImport } from './routes/captain/listings/$listingId'
import { Route as CaptainBoatsNewRouteImport } from './routes/captain/boats/new'
import { Route as CaptainBoatsBoatIdRouteImport } from './routes/captain/boats/$boatId'
import { Route as BookingConfirmationBookingIdRouteImport } from './routes/booking/confirmation/$bookingId'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainIndexRoute = CaptainIndexRouteImport.update({
  id: '/captain/',
  path: '/captain/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationIdRoute = ConversationIdRouteImport.update({
  id: '/conversation/$id',
  path: '/conversation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainOnboardingRoute = CaptainOnboardingRouteImport.update({
  id: '/captain/onboarding',
  path: '/captain/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainBookingsRoute = CaptainBookingsRouteImport.update({
  id: '/captain/bookings',
  path: '/captain/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingListingIdRoute = BookingListingIdRouteImport.update({
  id: '/booking/$listingId',
  path: '/booking/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainListingsIndexRoute = CaptainListingsIndexRouteImport.update({
  id: '/captain/listings/',
  path: '/captain/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainBoatsIndexRoute = CaptainBoatsIndexRouteImport.update({
  id: '/captain/boats/',
  path: '/captain/boats/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainListingsNewRoute = CaptainListingsNewRouteImport.update({
  id: '/captain/listings/new',
  path: '/captain/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainListingsListingIdRoute =
  CaptainListingsListingIdRouteImport.update({
    id: '/captain/listings/$listingId',
    path: '/captain/listings/$listingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaptainBoatsNewRoute = CaptainBoatsNewRouteImport.update({
  id: '/captain/boats/new',
  path: '/captain/boats/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainBoatsBoatIdRoute = CaptainBoatsBoatIdRouteImport.update({
  id: '/captain/boats/$boatId',
  path: '/captain/boats/$boatId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationBookingIdRoute =
  BookingConfirmationBookingIdRouteImport.update({
    id: '/booking/confirmation/$bookingId',
    path: '/booking/confirmation/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/trips': typeof TripsRoute
  '/booking/$listingId': typeof BookingListingIdRoute
  '/captain/bookings': typeof CaptainBookingsRoute
  '/captain/onboarding': typeof CaptainOnboardingRoute
  '/conversation/$id': typeof ConversationIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/captain/': typeof CaptainIndexRoute
  '/booking/confirmation/$bookingId': typeof BookingConfirmationBookingIdRoute
  '/captain/boats/$boatId': typeof CaptainBoatsBoatIdRoute
  '/captain/boats/new': typeof CaptainBoatsNewRoute
  '/captain/listings/$listingId': typeof CaptainListingsListingIdRoute
  '/captain/listings/new': typeof CaptainListingsNewRoute
  '/captain/boats/': typeof CaptainBoatsIndexRoute
  '/captain/listings/': typeof CaptainListingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/trips': typeof TripsRoute
  '/booking/$listingId': typeof BookingListingIdRoute
  '/captain/bookings': typeof CaptainBookingsRoute
  '/captain/onboarding': typeof CaptainOnboardingRoute
  '/conversation/$id': typeof ConversationIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/captain': typeof CaptainIndexRoute
  '/booking/confirmation/$bookingId': typeof BookingConfirmationBookingIdRoute
  '/captain/boats/$boatId': typeof CaptainBoatsBoatIdRoute
  '/captain/boats/new': typeof CaptainBoatsNewRoute
  '/captain/listings/$listingId': typeof CaptainListingsListingIdRoute
  '/captain/listings/new': typeof CaptainListingsNewRoute
  '/captain/boats': typeof CaptainBoatsIndexRoute
  '/captain/listings': typeof CaptainListingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/trips': typeof TripsRoute
  '/booking/$listingId': typeof BookingListingIdRoute
  '/captain/bookings': typeof CaptainBookingsRoute
  '/captain/onboarding': typeof CaptainOnboardingRoute
  '/conversation/$id': typeof ConversationIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/captain/': typeof CaptainIndexRoute
  '/booking/confirmation/$bookingId': typeof BookingConfirmationBookingIdRoute
  '/captain/boats/$boatId': typeof CaptainBoatsBoatIdRoute
  '/captain/boats/new': typeof CaptainBoatsNewRoute
  '/captain/listings/$listingId': typeof CaptainListingsListingIdRoute
  '/captain/listings/new': typeof CaptainListingsNewRoute
  '/captain/boats/': typeof CaptainBoatsIndexRoute
  '/captain/listings/': typeof CaptainListingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/inbox'
    | '/profile'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/trips'
    | '/booking/$listingId'
    | '/captain/bookings'
    | '/captain/onboarding'
    | '/conversation/$id'
    | '/listings/$id'
    | '/captain/'
    | '/booking/confirmation/$bookingId'
    | '/captain/boats/$boatId'
    | '/captain/boats/new'
    | '/captain/listings/$listingId'
    | '/captain/listings/new'
    | '/captain/boats/'
    | '/captain/listings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/inbox'
    | '/profile'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/trips'
    | '/booking/$listingId'
    | '/captain/bookings'
    | '/captain/onboarding'
    | '/conversation/$id'
    | '/listings/$id'
    | '/captain'
    | '/booking/confirmation/$bookingId'
    | '/captain/boats/$boatId'
    | '/captain/boats/new'
    | '/captain/listings/$listingId'
    | '/captain/listings/new'
    | '/captain/boats'
    | '/captain/listings'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/inbox'
    | '/profile'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/trips'
    | '/booking/$listingId'
    | '/captain/bookings'
    | '/captain/onboarding'
    | '/conversation/$id'
    | '/listings/$id'
    | '/captain/'
    | '/booking/confirmation/$bookingId'
    | '/captain/boats/$boatId'
    | '/captain/boats/new'
    | '/captain/listings/$listingId'
    | '/captain/listings/new'
    | '/captain/boats/'
    | '/captain/listings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  InboxRoute: typeof InboxRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TripsRoute: typeof TripsRoute
  BookingListingIdRoute: typeof BookingListingIdRoute
  CaptainBookingsRoute: typeof CaptainBookingsRoute
  CaptainOnboardingRoute: typeof CaptainOnboardingRoute
  ConversationIdRoute: typeof ConversationIdRoute
  ListingsIdRoute: typeof ListingsIdRoute
  CaptainIndexRoute: typeof CaptainIndexRoute
  BookingConfirmationBookingIdRoute: typeof BookingConfirmationBookingIdRoute
  CaptainBoatsBoatIdRoute: typeof CaptainBoatsBoatIdRoute
  CaptainBoatsNewRoute: typeof CaptainBoatsNewRoute
  CaptainListingsListingIdRoute: typeof CaptainListingsListingIdRoute
  CaptainListingsNewRoute: typeof CaptainListingsNewRoute
  CaptainBoatsIndexRoute: typeof CaptainBoatsIndexRoute
  CaptainListingsIndexRoute: typeof CaptainListingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/': {
      id: '/captain/'
      path: '/captain'
      fullPath: '/captain/'
      preLoaderRoute: typeof CaptainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/$id': {
      id: '/conversation/$id'
      path: '/conversation/$id'
      fullPath: '/conversation/$id'
      preLoaderRoute: typeof ConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/onboarding': {
      id: '/captain/onboarding'
      path: '/captain/onboarding'
      fullPath: '/captain/onboarding'
      preLoaderRoute: typeof CaptainOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/bookings': {
      id: '/captain/bookings'
      path: '/captain/bookings'
      fullPath: '/captain/bookings'
      preLoaderRoute: typeof CaptainBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$listingId': {
      id: '/booking/$listingId'
      path: '/booking/$listingId'
      fullPath: '/booking/$listingId'
      preLoaderRoute: typeof BookingListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/listings/': {
      id: '/captain/listings/'
      path: '/captain/listings'
      fullPath: '/captain/listings/'
      preLoaderRoute: typeof CaptainListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/boats/': {
      id: '/captain/boats/'
      path: '/captain/boats'
      fullPath: '/captain/boats/'
      preLoaderRoute: typeof CaptainBoatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/listings/new': {
      id: '/captain/listings/new'
      path: '/captain/listings/new'
      fullPath: '/captain/listings/new'
      preLoaderRoute: typeof CaptainListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/listings/$listingId': {
      id: '/captain/listings/$listingId'
      path: '/captain/listings/$listingId'
      fullPath: '/captain/listings/$listingId'
      preLoaderRoute: typeof CaptainListingsListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/boats/new': {
      id: '/captain/boats/new'
      path: '/captain/boats/new'
      fullPath: '/captain/boats/new'
      preLoaderRoute: typeof CaptainBoatsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/boats/$boatId': {
      id: '/captain/boats/$boatId'
      path: '/captain/boats/$boatId'
      fullPath: '/captain/boats/$boatId'
      preLoaderRoute: typeof CaptainBoatsBoatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirmation/$bookingId': {
      id: '/booking/confirmation/$bookingId'
      path: '/booking/confirmation/$bookingId'
      fullPath: '/booking/confirmation/$bookingId'
      preLoaderRoute: typeof BookingConfirmationBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  InboxRoute: InboxRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TripsRoute: TripsRoute,
  BookingListingIdRoute: BookingListingIdRoute,
  CaptainBookingsRoute: CaptainBookingsRoute,
  CaptainOnboardingRoute: CaptainOnboardingRoute,
  ConversationIdRoute: ConversationIdRoute,
  ListingsIdRoute: ListingsIdRoute,
  CaptainIndexRoute: CaptainIndexRoute,
  BookingConfirmationBookingIdRoute: BookingConfirmationBookingIdRoute,
  CaptainBoatsBoatIdRoute: CaptainBoatsBoatIdRoute,
  CaptainBoatsNewRoute: CaptainBoatsNewRoute,
  CaptainListingsListingIdRoute: CaptainListingsListingIdRoute,
  CaptainListingsNewRoute: CaptainListingsNewRoute,
  CaptainBoatsIndexRoute: CaptainBoatsIndexRoute,
  CaptainListingsIndexRoute: CaptainListingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
